/* automatically generated by rust-bindgen */

use OSQPSettings;

extern "C" {

    /// Set default settings from constants.h file
    /// assumes settings already allocated in memory
    /// @param settings settings structure

    #[link_name = "\u{1}_set_default_settings"]
    pub fn set_default_settings(settings: *mut OSQPSettings);
}
