#!/bin/bash

bindgen bindings.h -o src/bindings.rs \
--distrust-clang-mangling \
--no-layout-tests \
--no-recursive-allowlist \
--no-prepend-enum-name \
--raw-line "use {c_float, c_int, OSQPTimer};" \
--allowlist-type csc \
--allowlist-type LinSysSolver \
--allowlist-type OSQPScaling \
--allowlist-type OSQPSolution \
--allowlist-type OSQPInfo \
--allowlist-type OSQPPolish \
--allowlist-type OSQPData \
--allowlist-type OSQPSettings \
--allowlist-type OSQPWorkspace \
--allowlist-type linsys_solver \
--allowlist-type linsys_solver_type \
--allowlist-type osqp_error_type \
--allowlist-type ffi_osqp_solve_status \
--allowlist-function osqp_setup \
--allowlist-function osqp_solve \
--allowlist-function osqp_cleanup \
--allowlist-function osqp_update_lin_cost \
--allowlist-function osqp_update_bounds \
--allowlist-function osqp_update_lower_bound \
--allowlist-function osqp_update_upper_bound \
--allowlist-function osqp_warm_start \
--allowlist-function osqp_warm_start_x \
--allowlist-function osqp_warm_start_y \
--allowlist-function osqp_update_P \
--allowlist-function osqp_update_A \
--allowlist-function osqp_update_P_A \
--allowlist-function osqp_update_rho \
--allowlist-function osqp_update_max_iter \
--allowlist-function osqp_update_eps_abs \
--allowlist-function osqp_update_eps_rel \
--allowlist-function osqp_update_eps_prim_inf \
--allowlist-function osqp_update_eps_dual_inf \
--allowlist-function osqp_update_alpha \
--allowlist-function osqp_update_warm_start \
--allowlist-function osqp_update_scaled_termination \
--allowlist-function osqp_update_check_termination \
--allowlist-function osqp_update_delta \
--allowlist-function osqp_update_polish \
--allowlist-function osqp_update_polish_refine_iter \
--allowlist-function osqp_update_verbose \
--allowlist-function osqp_update_time_limit \
--allowlist-function osqp_set_default_settings \
