#!/bin/bash

bindgen bindings.h -o src/bindings.rs \
--rust-target 1.63 \
--distrust-clang-mangling \
--no-layout-tests \
--no-recursive-allowlist \
--no-prepend-enum-name \
--raw-line "use {OSQPFloat, OSQPInt};" \
--allowlist-type osqp_linsys_solver_type \
--allowlist-type osqp_precond_type \
--allowlist-type OSQPWorkspace_ \
--allowlist-type OSQPSolver \
--allowlist-type OSQPCscMatrix \
--allowlist-function OSQPCscMatrix_new \
--allowlist-function OSQPCscMatrix_free \
--allowlist-function OSQPSettings_new \
--allowlist-function OSQPSettings_free \
--allowlist-function osqp_version \
--allowlist-type osqp_status_type \
--allowlist-function osqp_update_data_vec \
--allowlist-function osqp_update_data_mat \
--allowlist-type csc \
--allowlist-type LinSysSolver \
--allowlist-type OSQPScaling \
--allowlist-type OSQPSolution \
--allowlist-type OSQPInfo \
--allowlist-type OSQPPolish \
--allowlist-type OSQPData \
--allowlist-type OSQPSettings \
--allowlist-type OSQPWorkspace \
--allowlist-type linsys_solver \
--allowlist-type linsys_solver_type \
--allowlist-type osqp_error_type \
--allowlist-type ffi_osqp_solve_status \
--allowlist-function osqp_setup \
--allowlist-function osqp_solve \
--allowlist-function osqp_cleanup \
--allowlist-function osqp_warm_start \
--allowlist-function osqp_warm_start_x \
--allowlist-function osqp_warm_start_y \
--allowlist-function osqp_update_rho \
--allowlist-function osqp_update_max_iter \
--allowlist-function osqp_update_eps_abs \
--allowlist-function osqp_update_eps_rel \
--allowlist-function osqp_update_eps_prim_inf \
--allowlist-function osqp_update_eps_dual_inf \
--allowlist-function osqp_update_alpha \
--allowlist-function osqp_update_warm_start \
--allowlist-function osqp_update_scaled_termination \
--allowlist-function osqp_update_check_termination \
--allowlist-function osqp_update_delta \
--allowlist-function osqp_update_polish \
--allowlist-function osqp_update_polish_refine_iter \
--allowlist-function osqp_update_verbose \
--allowlist-function osqp_update_time_limit \
--allowlist-function osqp_set_default_settings \
--allowlist-function osqp_update_settings \
