on: [push, pull_request]

name: Build and Test

jobs:
  # This is a hack so we don't have to gate PRs on each element of the build matrix.
  build-and-test-succeeded:
    name: Build and Test Succeeded
    needs: build-and-test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            channel: 1.63
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            channel: stable
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            channel: beta
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            channel: nightly

          - os: macos-13
            target: x86_64-apple-darwin
            channel: 1.63
          - os: macos-13
            target: x86_64-apple-darwin
            channel: stable

          - os: windows-2022
            target: x86_64-pc-windows-msvc
            channel: 1.63
          - os: windows-2022
            target: x86_64-pc-windows-msvc
            channel: stable

          - os: windows-2022
            target: i686-pc-windows-msvc
            channel: 1.63
          - os: windows-2022
            target: i686-pc-windows-msvc
            channel: stable
          - os: windows-2022
            target: i686-pc-windows-msvc
            channel: beta
          - os: windows-2022
            target: i686-pc-windows-msvc
            channel: nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          default: true
          toolchain: ${{ matrix.channel }}-${{ matrix.target }}

      - name: Build and Test (Debug)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --target ${{ matrix.target }}

      - name: Build and Test (Release)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all --target ${{ matrix.target }}
